### ISSUE TITLE
프론트엔드 cicd yml 환경변수 설정 부분 수정

### ISSUE THREAD

**Issue by yogjin** [woowacourse-teams/2023-dong-gle#148]
### ⏰ Estimated Time

0.5

### 🛠️ Description

- 프론트엔드 cicd 설정

### ✅ Tasks

- cicd yml 환경변수 설정 부분 수정

### 📝 Note

```yml
      - name: Create .env.development variable
        run: touch .env.development
          echo "BASE_URL=${{secrets.BASE_URL_DEVELOPMENT}}" >> .env.development
```
명령어 `touch`, `echo` 두 개를 해야하기 때문에 기존 위 job의 run을 아래와 같이 `|` 로 연결해야할 것 같아요
```yml
    - name: Create .env.development variable
        run: |
          touch .env.development
          echo "BASE_URL=${{secrets.BASE_URL_DEVELOPMENT}}" >> .env.development
```
